#ifndef PROTODEF

#else
PROTODEF(PROTOCOL_FLYSKY, A7105, AETRG, FLYSKY_Cmds, "Flysky")
PROTODEF(PROTOCOL_AFHDS2A, A7105, AETRG, AFHDS2A_Cmds, "AFHDS-2A")
PROTODEF(PROTOCOL_HUBSAN, A7105, AETRG, HUBSAN_Cmds, "Hubsan4")
PROTODEF(PROTOCOL_JOYSWAY, A7105, AETRG, JOYSWAY_Cmds, "Joysway")
PROTODEF(PROTOCOL_BUGS3, A7105, AETRG, BUGS3_Cmds, "Bugs3")
#endif
